### ISSUE TITLE
-

### ISSUE THREAD

**Issue by cuj** [tangrs/nspire-linux-loader2#13]
>

**Comment by hazelduvall** [comment]
@IIWare It looks like you'll need to compile the code yourself. See <https://hackspire.org/index.php/C_and_assembly_development_introduction> for how to install the Ndless toolchain, and then you should just be able to run `make all` in the root directory of this project.

**Comment by cuj** [comment]
@duvallj sorry I haven't responded in a while, anyways when I ran `make all` in macOS Big sur 11.0 (20A5374i) here's the error I got:
```
MacBook-Pro:nspire-linux-loader2 macbookair$ make all
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
nspire-gcc -DBUILD_DATE="\"\"" -DGIT_COMMIT="\"ca31ca0\"" -mcpu=arm926ej-s -Os -nostdlib -Wall -Werror -marm -Ilibfdt/ -c atag.c -o atag.o
/bin/sh: nspire-gcc: command not found
make: *** [atag.o] Error 127
```
if macOS big sur is incompatible to make, then which other mac/linux version can I use to run `make all`? thanks.

**Comment by hazelduvall** [comment]
@cuj From the error log, it looks like you didn't install the ndless toolchain properly (`/bin/sh: nspire-gcc: command not found` == nspire-gcc, the tool used to compile programs for the nspire, is not on your `$PATH`).
I have not used macOS Big Sur to compile the Ndless toolchain before, but you should be able to install all the dependencies with `brew` and follow <https://hackspire.org/index.php/C_and_assembly_development_introduction> to get the toolchain installed.

**Comment by cuj** [comment]
@duvallj i've installed nspire-gcc successfully, however I ran into another error when I did `make all` in the root directory of the linux loader source code, there's an error `/bin/sh: genzehn: command not found` also `brew install genzehn` didn't work, so can you please tell me how to install `genzehn` or at least tell me how to fix the issue? thanks.

**Comment by hazelduvall** [comment]
@cuj `genzehn` (and another program you will need, `make-prg`) are Ndless SDKprograms used to take an ELF executable and turn it into a .tns executable. Searching for `genzehn` in the Ndless SDK gives [this folder](https://github.com/ndless-nspire/Ndless/tree/master/ndless-sdk/tools). If you run `make all` in there it should install `genzehn` and `make-prg` in the same bin path as the `nspire-gcc` tool.
If you get stuck again, please try a bit harder to work through it yourself.
