### ISSUE TITLE
Attempt at booting on CXII CAS

### ISSUE THREAD

**Issue by mj-sakellaropoulos** [tangrs/nspire-linux-loader2#14]
I just tried it using latest files and busybox initrd from [ti-planet](https://tiplanet.org/nspire_linux_builds/).

It almost works! I even have a console cursor, but hardware for LCD and others are different.

Am wondering what areas need changes for CXII support ?

(photo of calc, the garbled text gradually printed out in a way similar to the actual boot text)
![image](https://user-images.githubusercontent.com/36081545/114965756-40124700-9e3f-11eb-98a6-8f9a66f3e1a5.png)

**Comment by mj-sakellaropoulos** [comment]
This is now working with https://github.com/vogtinator/linux/tree/cxII-clean, closing.

**Comment by Xenthio** [comment]
can you send me the build you created? i cant be bothered to build it myself with my shit hardware

**Comment by mj-sakellaropoulos** [comment]
Vogtinator updated the build here (only linux loader) https://tiplanet.org/nspire-linux-builds/

If you mean the kernel, using Vogtinator's defconfig, it should compile pretty quick since its so minimal.

My build of the kernel is not fully working yet.
