### ISSUE TITLE
How can I use the built in keyboard?

### ISSUE THREAD

**Issue by ryanknutson** [tangrs/nspire-linux-loader2#4]
Linux boots fine, but when I try to use the keyboard on the calculator, it doesn't work. Any way how I can enable this/get it to work?

Also, how can I enable USB-OTG? I'm not very good at kernel stuff. I have a CX (not CAS).

**Comment by ryanknutson** [comment]
Also, how can I enable USB-OTG? I'm not very good at kernel stuff. I have a CX (not CAS).

**Comment by tangrs** [comment]
Please see https://hackspire.unsads.com/index.php/Linux
This issues board is strictly for issues and bugs relating to the code. If you need help, please refer to the links in the Wiki above.
