### ISSUE TITLE
Please add a precompiled linuxloader.tns

### ISSUE THREAD

**Issue by LeoDJ** [tangrs/nspire-linux-loader2#5]
I am currently struggling to compile the linuxloader. First I had many troubles getting nspire-gcc to work, and now it has various errors when I try to make linuxloader.

I could explain everything and eventually figure things out, but I have a much easier question:
Can you please add a download to a compiled version of your linuxloader.tns?

**Comment by tangrs** [comment]
There are builds of everything you need to run Linux on [the TI-Planet build servers](http://tiplanet.org/nspire-linux-builds/).
